### ISSUE TITLE
Problem: automatically generate SUMMARY.md

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/rfc#12]
Gitbook do support template language (https://toolchain.gitbook.com/themes/). Can we find a way to utilize it so SUMMARY.md can be generated?

**Comment by sjmackenzie** [comment]
Erk, I strongly suggest we change SUMMARY.md by hand. The automatic process won't know when an RFC becomes stable (for example).

**Comment by sjmackenzie** [comment]
closing as one just needs to remember to update SUMMARY.md
