### ISSUE TITLE
Problem: Gitbook comments is buggy

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/rfc#9]
I occasionally get the "Error with inline comments" popup error when trying to access the rendered page. Please disable gitbook comment feature (in the gitbook settings page, I suppose).

**Comment by sjmackenzie** [comment]
yeah, once we get a `rfc.ethereumclassic.org` then point all the domain tags in each of the documents to that it should be fine.

**Comment by sjmackenzie** [comment]
I'll see if i can disable that

**Comment by sjmackenzie** [comment]
okay disabled `comments` and `inline whatever`

**Comment by sjmackenzie** [comment]
okay that problem is solved.

**Comment by sjmackenzie** [comment]
it's back even after disabling ...

**Comment by sjmackenzie** [comment]
I think it's related to not having a `rfc.ethereumclassic.org` domain yet. bah let's see
